# Generated by Django 4.1.5 on 2023-04-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS shop AUTHORIZATION postgres;")
    ]
