# Generated by Django 4.1.5 on 2023-04-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_create_shop_schema"),
    ]

    operations = [
        migrations.RunSQL("ALTER DATABASE postgres SET search_path TO shop, public;")
    ]
