# Generated by Django 4.2 on 2023-07-24 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_change_search_path"),
    ]

    operations = [
        # because Django's default initial migrations applies before schema changes
        migrations.RunSQL(
            """
            DO LANGUAGE plpgsql
            $body$
            DECLARE
               l_old_schema NAME = 'public';
               l_new_schema NAME = 'shop';
               l_sql TEXT;
            BEGIN
              FOR l_sql IN
                SELECT 
                    format('ALTER TABLE %I.%I SET SCHEMA %I', n.nspname, c.relname, l_new_schema)
                  FROM pg_class c
                  JOIN pg_namespace n ON n.oid = c.relnamespace
                  WHERE
                    n.nspname = l_old_schema AND
                    c.relkind = 'r'
              LOOP
                RAISE NOTICE 'appliying %', l_sql;
                EXECUTE l_sql;
              END LOOP;
            END;
            $body$;
            """
        )
    ]
