---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.

version: '3.8'
name: "django-shop"

services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres-shop
    environment:
      PGDATESTYLE: ISO  # ISO, SQL, Postgres, German
    ports:
     - 5432:5432 
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0
    volumes:
      - db-shop:/var/lib/postgresql/data
    shm_size: '2gb'

  redis:
    image: redis:6-alpine
    container_name: redis-shop
    ports:
      - 6379:6379

volumes:
  db-shop:
    name: "db-shop"
