---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.

version: '3.8'
name: "django-shop"

services:
  # django:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/src

  postgres:
    image: postgres:13-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATESTYLE: ISO  # ISO, SQL, Postgres, German
    ports:
     - 5432:5432 
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0
    volumes:
      - dev-db:/var/lib/postgresql/data
    shm_size: '2gb'

  redis:
    image: redis:6-alpine
    container_name: redis-dev
    ports:
      - 6379:6379

volumes:
  dev-db:
  # external: true
    name: "dev-db"
