---

# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker compose up

version: '3.8'
name: "django-shop-dev"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: django-dev
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
        - action: rebuild
          path: dev-requirements.txt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pg-admin
    ports:
      - '5555:80'  # http://localhost:5555/
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-dev:/var/lib/pgadmin

volumes:
  pgadmin-dev:
    name: "pgadmin-dev"
