---

# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker compose up

version: '3.8'
name: "django-shop-dev"

services:
  pgadmin:
    image: dpage/pgadmin4:7.6
    # restart: always
    container_name: pg-admin
    ports:
      - '5555:80'  # http://localhost:5555/
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-dev:/var/lib/pgadmin

volumes:
  pgadmin-dev:
  # external: true
    name: "pgadmin-dev"
