# Generated by Django 4.2 on 2023-07-08 17:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="option",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("DE", "Germany"),
                    ("TR", "Turkey"),
                    ("AE", "United Arab Emirates"),
                    ("TH", "Thailand"),
                    ("JP", "Japan"),
                ],
                default="US",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
