# Generated by Django 4.2 on 2023-06-28 17:04

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models
import django.db.models.deletion

import app.files
import products.models.products


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (None, "Select category"),
                            (
                                "Dresses",
                                (("man", "Men's Dresses"), ("woman", "Women's Dresses"), ("baby", "Baby's Dresses")),
                            ),
                            ("shirts", "Shirts"),
                            ("jeans", "Jeans"),
                            ("swimwear", "Swimwear"),
                            ("sleepwear", "Sleepwear"),
                            ("sportswear", "Sportswear"),
                            ("jumpsuits", "Jumpsuits"),
                            ("blazers", "Blazers"),
                            ("jackets", "Jackets"),
                            ("shoes", "Shoes"),
                        ],
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="category")),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("image", models.ImageField(upload_to=app.files.RandomFileName("product/%Y/%m/%d/"))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("information", models.TextField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                ("public_id", models.UUIDField(editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("option", models.JSONField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.IntegerField(default=0, validators=[products.models.products.validate_discount])),
                ("quantity", models.PositiveIntegerField()),
                ("available", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            (None, "Rate product"),
                            ("1", "1 star"),
                            ("2", "2 stars"),
                            ("3", "3 stars"),
                            ("4", "4 stars"),
                            ("5", "5 stars"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="products.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
