# Generated by Django 4.2 on 2023-07-03 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productoption",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="productvariant",
            old_name="product_id",
            new_name="product",
        ),
    ]
