# Generated by Django 4.2 on 2023-07-06 14:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_create_product_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.SmallIntegerField(
                choices=[
                    (None, "Rate product"),
                    ("1", "1 star"),
                    ("2", "2 stars"),
                    ("3", "3 stars"),
                    ("4", "4 stars"),
                    ("5", "5 stars"),
                ]
            ),
        ),
    ]
