# Generated by Django 4.2 on 2023-07-13 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="date",
        ),
    ]
