# Generated by Django 4.2 on 2023-07-15 15:49

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
